

import type { SalesManagerLead } from "@/schema/SalesManagerLeadSchema";
export const SalesManagerLeadData: SalesManagerLead[] = [
    {
        "leadId": "LD-2024-001",
        "clientType": "new",
        "sourceOfLead": "email",
        "customerName": "Rajesh Kumar",
        "customerCompanyName": "GreenTech Solutions Pvt Ltd",
        "customerContactNumber": "+91-9876543210",
        "inquiryLocation": "north",
        "category": "ambient",
        "requirement": "Ambient air quality monitoring station",
        "remark": "Client needs installation within 30 days",
        "enquiryStatus": "pending",
        "salesManager": "Amit Sharma",
        "serviceManager": "Priya Singh",
        "technicalFieldEngineer": "Rohit Verma",
        "inspectionStatus": "pending",
        "quoteAmount": 1250000,
        "quoteAttached": false,
        "attachedPO": false,
        "attachedPI": false
    },
    {
        "leadId": "LD-2024-002",
        "clientType": "existing",
        "sourceOfLead": "inbound call",
        "customerName": "Sunita Patel",
        "customerCompanyName": "CleanWater Industries",
        "customerContactNumber": "+91-8765432109",
        "inquiryLocation": "west",
        "category": "effluent",
        "requirement": "Effluent treatment plant monitoring system",
        "remark": "Follow up required next week",
        "enquiryStatus": "call done",
        "closeRemark": "Client requested detailed proposal",
        "salesManager": "Neha Gupta",
        "serviceManager": "Sanjay Mehta",
        "technicalFieldEngineer": "Vikram Joshi",
        "inspectionStatus": "progress",
        "quoteAmount": 850000,
        "quoteAttached": true,
        "attachedPO": false,
        "attachedPI": false
    },
    {
        "leadId": "LD-2024-003",
        "clientType": "new",
        "sourceOfLead": "outbound call",
        "customerName": "Anil Desai",
        "customerCompanyName": "EcoMonitor Systems",
        "customerContactNumber": "+91-7654321098",
        "inquiryLocation": "south",
        "category": "emission",
        "requirement": "Stack emission monitoring equipment",
        "enquiryStatus": "close",
        "closeRemark": "Project awarded to competitor",
        "salesManager": "Kiran Reddy",
        "inspectionStatus": "done",
        "quoteAmount": 950000,
        "quoteAttached": true,
        "attachedPO": false,
        "poDate": "2024-01-15",
        "attachedPI": true
    },
    {
        "leadId": "LD-2024-004",
        "clientType": "existing",
        "sourceOfLead": "email",
        "customerName": "Meera Iyer",
        "customerCompanyName": "AquaPure Technologies",
        "customerContactNumber": "+91-6543210987",
        "inquiryLocation": "east",
        "category": "RTWQMS",
        "requirement": "Real-time water quality monitoring system for river",
        "remark": "Government project - high priority",
        "enquiryStatus": "pending",
        "salesManager": "Arun Banerjee",
        "quoteAmount": 2150000,
        "quoteAttached": false,
        "attachedPO": false,
        "attachedPI": false
    },
    {
        "leadId": "LD-2024-005",
        "clientType": "new",
        "sourceOfLead": "inbound call",
        "customerName": "Vikram Singh",
        "customerCompanyName": "Metro Power Corporation",
        "customerContactNumber": "+91-9432109876",
        "inquiryLocation": "north",
        "category": "ambient",
        "requirement": "Portable ambient air quality monitors (10 units)",
        "enquiryStatus": "call done",
        "salesManager": "Amit Sharma",
        "technicalFieldEngineer": "Rahul Kapoor",
        "inspectionStatus": "progress",
        "quoteAmount": 750000,
        "quoteAttached": true,
        "attachedPO": true,
        "poDate": "2024-01-20",
        "attachedPI": true
    }
];

